management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true  # endpoint.info.env vs endpoint.env
    git:
      enabled: true
      mode: FULL
    build:
      enabled: true  # info.git.build vs endpoint.build
    java:
      enabled: true
    os:
      enabled: true

  endpoint:
    env:
      show-values: ALWAYS

info:
  my-app:
    any-value: someValue
    group-id: "@project.groupId@"
    artifact-id: "@project.artifactId@"